version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - echo "Installing dependencies for Lambda 1..."
      - pip install -r lambda1/requirements.txt -t lambda1/lib

      - echo "Installing dependencies for Lambda 2..."
      - pip install -r lambda2/requirements.txt -t lambda2/lib

  build:
    commands:
      - echo "Packaging Lambda 1: produce-booking-data..."
      - cd lambda1/lib
      - zip -r9 ../../produce_booking_package.zip .
      - cd ..
      - zip -g ../produce_booking_package.zip producer_lambda.py
      - cd ..

      - echo "Packaging Lambda 2: processFilteredBookings..."
      - cd lambda2/lib
      - zip -r9 ../../process_filtered_package.zip .
      - cd ..
      - zip -g ../process_filtered_package.zip processFilteredBooking.py
      - cd ..

  post_build:
    commands:
      - echo "Uploading ZIPs to S3..."
      - aws s3 cp produce_booking_package.zip s3://lamda-zip-for-codebuild/
      - aws s3 cp process_filtered_package.zip s3://lamda-zip-for-codebuild/

      - echo "Updating Lambda functions via S3..."
      - aws lambda update-function-code --function-name produce-booking-data --s3-bucket lamda-zip-for-codebuild --s3-key produce_booking_package.zip
      - aws lambda update-function-code --function-name processFilteredBookings --s3-bucket lamda-zip-for-codebuild --s3-key process_filtered_package.zip

      - echo "Deployment complete!"
